<?php

/**
 * Implementation of hook_menu().
 */
function riot_github_hooks_menu() {
  $items = array();

  $items['github-hooks'] = array(
    'title' => 'Github integration',
    'description' => 'Automated testing Github integration.',
    'page callback' => 'riot_github_hooks_get_post',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function riot_github_hooks_get_post() {
    $post_parameters = '"payload" parameter is undefined.';
    $get_parameters = $_GET;
    if (isset($_POST['payload'])) {
      $post_parameters = json_decode($_POST['payload']);
    }
    $headers = getallheaders();
    watchdog('riot_github_hooks', '@headers --- @post --- @get', array(
                                                                       '@post' => var_export($post_parameters),
                                                                       '@headers' => var_export($headers),
                                                                       '@get' => var_export($get_parameters)), WATCHDOG_NOTICE);
    return t('Use this url to configure Github.');
}