<?php

/**
 * Implementation of hook_menu().
 */
function riot_github_hooks_menu() {
  $items = array();

  $items['github-hooks'] = array(
    'title' => 'Github integration',
    'description' => 'Automated testing Github integration.',
    'page callback' => 'riot_github_hooks_get_post',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function riot_github_hooks_get_post() {
    $post_parameters = $_POST;
    watchdog('tmgmt_microsoft', '@post', array('@post' => print_r($post_parameters)), WATCHDOG_NOTICE);
    print t('Use this url to configure Github.');
}